export const ACTIONS = {
  API_REQUEST: 'API_REQUEST',
  FETCH_ARTICLES: 'FETCH_ARTICLES',
  FETCH_ARTICLE: 'FETCH_ARTICLE',
  FETCH_MAININFO: 'FETCH_MAININFO',
  ADD_ARTICLE: 'ADD_ARTICLE',
  DELETE_ARTICLE: 'DELETE_ARTICLE',
  EDIT_ARTICLE: 'EDIT_ARTICLE',
  ERROR: 'ERROR'
}